### ISSUE TITLE
Koa-Prometheus missing prom-client module

### ISSUE THREAD

**Issue by shane-lab** [sigfox/javascript#14]
Unfortunately, the `prom-client` module is listed under dev dependencies.

```sh
internal/modules/cjs/loader.js:1017
  throw err;
  ^

Error: Cannot find module 'prom-client'
```

I just wanted to address that here.

**Comment by jeremiergz** [comment]
Hi! Thanks for creating the issue.

But as you can see [here](https://github.com/sigfox/javascript/blob/master/packages/koa-prometheus/package.json), `prom-client` is also listed under `peerDependencies`, therefore `npm` must have warned you during the installation that you were missing this module and should install it yourself.

Listing it under `peerDependencies` is more flexible as you're responsible for installing the version you want.

Hope this helps!

**Comment by shane-lab** [comment]
Hi, thanks for your quick reply. 

I see. It surely does make more sense now, as you probably intent to use the dev dependency for your tests. Most of the apps we build are in express and I was eagerly looking for a package in koa. By looking at the source, your package does what I need it to do for this one-off project. I am using yarn, it doesn't list peer dependencies when adding a new package.

**Comment by jeremiergz** [comment]
You're totally right, we use it as devDependency for our tests. Thanks for reporting this about Yarn, I didn't know that and it made me realize that we should add the peerDependency install step to the README.

Thanks!
